author: Borgdude
description: "${project.artifactId}"
main: com.borgdude.lives.SimpleLives
name: ${project.artifactId}
version: "${project.version}"
api-version: 1.13
softdepend: [Vault]

commands:
  lives:
    description: SimpleLives command
    usage: /<command> <options> | /<command> help